part of 'enums.dart';

/// An enumeration representing the available language types in the application.
enum LanguageType {
  afghanistanPashto('Afghanistan', 'Pashto', 'ps', 'AF', 'ps', 'AFG'),
  afghanistanPersian('Afghanistan', 'Persian', 'fa', 'AF', 'fa', 'AFG'),
  afghanistanUzbek('Afghanistan', 'Uzbek', 'uz', 'AF', 'uz', 'AFG'),
  landIslandsSwedish('Åland Islands', 'Swedish', 'sv', 'AX', 'sv', 'ALA'),
  albaniaAlbanian('Albania', 'Albanian', 'sq', 'AL', 'sq', 'ALB'),
  albaniaEnglish('Albania', 'English', 'en', 'AL', 'en', 'ALB'),
  algeriaArabic('Algeria', 'Arabic', 'ar', 'DZ', 'ar', 'DZA'),
  algeriaFrench('Algeria', 'French', 'fr', 'DZ', 'fr', 'DZA'),
  algeriaKabyle('Algeria', 'Kabyle', 'kab', 'DZ', 'kab', 'DZA'),
  americanSamoaEnglish('American Samoa', 'English', 'en', 'AS', 'en', 'ASM'),
  andorraCatalan('Andorra', 'Catalan', 'ca', 'AD', 'ca', 'AND'),
  andorraEnglish('Andorra', 'English', 'en', 'AD', 'en', 'AND'),
  angolaLingala('Angola', 'Lingala', 'ln', 'AO', 'ln', 'AGO'),
  angolaPortuguese('Angola', 'Portuguese', 'pt', 'AO', 'pt', 'AGO'),
  anguillaEnglish('Anguilla', 'English', 'en', 'AI', 'en', 'AIA'),
  anguillaSpanish('Anguilla', 'Spanish', 'es', 'AI', 'es', 'AIA'),
  antiguaBarbudaEnglish('Antigua & Barbuda', 'English', 'en', 'AG', 'en', 'ATG'),
  antiguaBarbudaSpanish('Antigua & Barbuda', 'Spanish', 'es', 'AG', 'es', 'ATG'),
  argentinaEnglish('Argentina', 'English', 'en', 'AR', 'en', 'ARG'),
  argentinaSpanish('Argentina', 'Spanish', 'es', 'AR', 'es', 'ARG'),
  armeniaArmenian('Armenia', 'Armenian', 'hy', 'AM', 'hy', 'ARM'),
  arubaDutch('Aruba', 'Dutch', 'nl', 'AW', 'nl', 'ABW'),
  arubaSpanish('Aruba', 'Spanish', 'es', 'AW', 'es', 'ABW'),
  australiaEnglish('Australia', 'English', 'en', 'AU', 'en', 'AUS'),
  austriaEnglish('Austria', 'English', 'en', 'AT', 'en', 'AUT'),
  austriaGerman('Austria', 'German', 'de', 'AT', 'de', 'AUT'),
  azerbaijanAzerbaijani('Azerbaijan', 'Azerbaijani', 'az', 'AZ', 'az', 'AZE'),
  bahamasEnglish('Bahamas', 'English', 'en', 'BS', 'en', 'BHS'),
  bahamasSpanish('Bahamas', 'Spanish', 'es', 'BS', 'es', 'BHS'),
  bahrainArabic('Bahrain', 'Arabic', 'ar', 'BH', 'ar', 'BHR'),
  bangladeshBangla('Bangladesh', 'Bangla', 'bn', 'BD', 'bn', 'BGD'),
  bangladeshChakma('Bangladesh', 'Chakma', 'ccp', 'BD', 'ccp', 'BGD'),
  bangladeshEnglish('Bangladesh', 'English', 'en', 'BD', 'en', 'BGD'),
  barbadosEnglish('Barbados', 'English', 'en', 'BB', 'en', 'BRB'),
  barbadosSpanish('Barbados', 'Spanish', 'es', 'BB', 'es', 'BRB'),
  belarusBelarusian('Belarus', 'Belarusian', 'be', 'BY', 'be', 'BLR'),
  belarusRussian('Belarus', 'Russian', 'ru', 'BY', 'ru', 'BLR'),
  belgiumDutch('Belgium', 'Dutch', 'nl', 'BE', 'nl', 'BEL'),
  belgiumEnglish('Belgium', 'English', 'en', 'BE', 'en', 'BEL'),
  belgiumFrench('Belgium', 'French', 'fr', 'BE', 'fr', 'BEL'),
  belgiumGerman('Belgium', 'German', 'de', 'BE', 'de', 'BEL'),
  belgiumWalloon('Belgium', 'Walloon', 'wa', 'BE', 'wa', 'BEL'),
  belizeEnglish('Belize', 'English', 'en', 'BZ', 'en', 'BLZ'),
  belizeSpanish('Belize', 'Spanish', 'es', 'BZ', 'es', 'BLZ'),
  beninFrench('Benin', 'French', 'fr', 'BJ', 'fr', 'BEN'),
  beninYoruba('Benin', 'Yoruba', 'yo', 'BJ', 'yo', 'BEN'),
  bermudaEnglish('Bermuda', 'English', 'en', 'BM', 'en', 'BMU'),
  bermudaSpanish('Bermuda', 'Spanish', 'es', 'BM', 'es', 'BMU'),
  bhutanDzongkha('Bhutan', 'Dzongkha', 'dz', 'BT', 'dz', 'BTN'),
  boliviaQuechua('Bolivia', 'Quechua', 'qu', 'BO', 'qu', 'BOL'),
  boliviaSpanish('Bolivia', 'Spanish', 'es', 'BO', 'es', 'BOL'),
  bosniaHerzegovinaBosnian('Bosnia & Herzegovina', 'Bosnian', 'bs', 'BA', 'bs', 'BIH'),
  bosniaHerzegovinaCroatian('Bosnia & Herzegovina', 'Croatian', 'hr', 'BA', 'hr', 'BIH'),
  bosniaHerzegovinaEnglish('Bosnia & Herzegovina', 'English', 'en', 'BA', 'en', 'BIH'),
  bosniaHerzegovinaSerbian('Bosnia & Herzegovina', 'Serbian', 'sr', 'BA', 'sr', 'BIH'),
  botswanaEnglish('Botswana', 'English', 'en', 'BW', 'en', 'BWA'),
  botswanaTswana('Botswana', 'Tswana', 'tn', 'BW', 'tn', 'BWA'),
  brazilEnglish('Brazil', 'English', 'en', 'BR', 'en', 'BRA'),
  brazilPortuguese('Brazil', 'Portuguese', 'pt', 'BR', 'pt', 'BRA'),
  brazilSpanish('Brazil', 'Spanish', 'es', 'BR', 'es', 'BRA'),
  britishIndianOceanTerritoryEnglish('British Indian Ocean Territory', 'English', 'en', 'IO', 'en', 'IOT'),
  britishVirginIslandsEnglish('British Virgin Islands', 'English', 'en', 'VG', 'en', 'VGB'),
  britishVirginIslandsSpanish('British Virgin Islands', 'Spanish', 'es', 'VG', 'es', 'VGB'),
  bruneiMalay('Brunei', 'Malay', 'ms', 'BN', 'ms', 'BRN'),
  bulgariaBulgarian('Bulgaria', 'Bulgarian', 'bg', 'BG', 'bg', 'BGR'),
  bulgariaEnglish('Bulgaria', 'English', 'en', 'BG', 'en', 'BGR'),
  burkinaFasoFrench('Burkina Faso', 'French', 'fr', 'BF', 'fr', 'BFA'),
  burkinaFasoFulah('Burkina Faso', 'Fulah', 'ff', 'BF', 'ff', 'BFA'),
  burundiEnglish('Burundi', 'English', 'en', 'BI', 'en', 'BDI'),
  burundiFrench('Burundi', 'French', 'fr', 'BI', 'fr', 'BDI'),
  burundiRundi('Burundi', 'Rundi', 'rn', 'BI', 'rn', 'BDI'),
  cambodiaKhmer('Cambodia', 'Khmer', 'km', 'KH', 'km', 'KHM'),
  cameroonAghem('Cameroon', 'Aghem', 'agq', 'CM', 'agq', 'CMR'),
  cameroonBafia('Cameroon', 'Bafia', 'ksf', 'CM', 'ksf', 'CMR'),
  cameroonBasaa('Cameroon', 'Basaa', 'bas', 'CM', 'bas', 'CMR'),
  cameroonDuala('Cameroon', 'Duala', 'dua', 'CM', 'dua', 'CMR'),
  cameroonEnglish('Cameroon', 'English', 'en', 'CM', 'en', 'CMR'),
  cameroonEwondo('Cameroon', 'Ewondo', 'ewo', 'CM', 'ewo', 'CMR'),
  cameroonFrench('Cameroon', 'French', 'fr', 'CM', 'fr', 'CMR'),
  cameroonFulah('Cameroon', 'Fulah', 'ff', 'CM', 'ff', 'CMR'),
  cameroonKako('Cameroon', 'Kako', 'kkj', 'CM', 'kkj', 'CMR'),
  cameroonKwasio('Cameroon', 'Kwasio', 'nmg', 'CM', 'nmg', 'CMR'),
  cameroonMeta('Cameroon', 'Meta\'', 'mgo', 'CM', 'mgo', 'CMR'),
  cameroonMundang('Cameroon', 'Mundang', 'mua', 'CM', 'mua', 'CMR'),
  cameroonNgiemboon('Cameroon', 'Ngiemboon', 'nnh', 'CM', 'nnh', 'CMR'),
  cameroonNgomba('Cameroon', 'Ngomba', 'jgo', 'CM', 'jgo', 'CMR'),
  cameroonYangben('Cameroon', 'Yangben', 'yav', 'CM', 'yav', 'CMR'),
  canadaEnglish('Canada', 'English', 'en', 'CA', 'en', 'CAN'),
  canadaFrench('Canada', 'French', 'fr', 'CA', 'fr', 'CAN'),
  canadaInuktitut('Canada', 'Inuktitut', 'iu', 'CA', 'iu', 'CAN'),
  canadaMohawk('Canada', 'Mohawk', 'moh', 'CA', 'moh', 'CAN'),
  canadaSpanish('Canada', 'Spanish', 'es', 'CA', 'es', 'CAN'),
  canaryIslandsSpanish('Canary Islands', 'Spanish', 'es', 'IC', 'es', 'IC'),
  capeVerdeKabuverdianu('Cape Verde', 'Kabuverdianu', 'kea', 'CV', 'kea', 'CPV'),
  capeVerdePortuguese('Cape Verde', 'Portuguese', 'pt', 'CV', 'pt', 'CPV'),
  caribbeanNetherlandsDutch('Caribbean Netherlands', 'Dutch', 'nl', 'BQ', 'nl', 'BES'),
  caribbeanNetherlandsSpanish('Caribbean Netherlands', 'Spanish', 'es', 'BQ', 'es', 'BES'),
  caymanIslandsEnglish('Cayman Islands', 'English', 'en', 'KY', 'en', 'CYM'),
  caymanIslandsSpanish('Cayman Islands', 'Spanish', 'es', 'KY', 'es', 'CYM'),
  centralAfricanRepublicFrench('Central African Republic', 'French', 'fr', 'CF', 'fr', 'CAF'),
  centralAfricanRepublicLingala('Central African Republic', 'Lingala', 'ln', 'CF', 'ln', 'CAF'),
  centralAfricanRepublicSango('Central African Republic', 'Sango', 'sg', 'CF', 'sg', 'CAF'),
  ceutaMelillaSpanish('Ceuta & Melilla', 'Spanish', 'es', 'EA', 'es', 'EA'),
  chadArabic('Chad', 'Arabic', 'ar', 'TD', 'ar', 'TCD'),
  chadFrench('Chad', 'French', 'fr', 'TD', 'fr', 'TCD'),
  chileEnglish('Chile', 'English', 'en', 'CL', 'en', 'CHL'),
  chileMapuche('Chile', 'Mapuche', 'arn', 'CL', 'arn', 'CHL'),
  chileSpanish('Chile', 'Spanish', 'es', 'CL', 'es', 'CHL'),
  chinaMainlandCantonese('China mainland', 'Cantonese', 'yue', 'CN', 'yue', 'CHN'),
  chinaMainlandChinese('China mainland', 'Chinese', 'zh', 'CN', 'zh', 'CHN'),
  chinaMainlandEnglish('China mainland', 'English', 'en', 'CN', 'en', 'CHN'),
  chinaMainlandSichuanYi('China mainland', 'Sichuan Yi', 'ii', 'CN', 'ii', 'CHN'),
  chinaMainlandTibetan('China mainland', 'Tibetan', 'bo', 'CN', 'bo', 'CHN'),
  chinaMainlandUyghur('China mainland', 'Uyghur', 'ug', 'CN', 'ug', 'CHN'),
  christmasIslandEnglish('Christmas Island', 'English', 'en', 'CX', 'en', 'CXR'),
  cocosKeelingIslandsEnglish('Cocos (Keeling) Islands', 'English', 'en', 'CC', 'en', 'CCK'),
  colombiaEnglish('Colombia', 'English', 'en', 'CO', 'en', 'COL'),
  colombiaSpanish('Colombia', 'Spanish', 'es', 'CO', 'es', 'COL'),
  comorosArabic('Comoros', 'Arabic', 'ar', 'KM', 'ar', 'COM'),
  comorosFrench('Comoros', 'French', 'fr', 'KM', 'fr', 'COM'),
  congoBrazzavilleFrench('Congo - Brazzaville', 'French', 'fr', 'CG', 'fr', 'COG'),
  congoBrazzavilleLingala('Congo - Brazzaville', 'Lingala', 'ln', 'CG', 'ln', 'COG'),
  congoKinshasaFrench('Congo - Kinshasa', 'French', 'fr', 'CD', 'fr', 'COD'),
  congoKinshasaLingala('Congo - Kinshasa', 'Lingala', 'ln', 'CD', 'ln', 'COD'),
  congoKinshasaLubaKatanga('Congo - Kinshasa', 'Luba-Katanga', 'lu', 'CD', 'lu', 'COD'),
  congoKinshasaSwahili('Congo - Kinshasa', 'Swahili', 'sw', 'CD', 'sw', 'COD'),
  cookIslandsEnglish('Cook Islands', 'English', 'en', 'CK', 'en', 'COK'),
  costaRicaSpanish('Costa Rica', 'Spanish', 'es', 'CR', 'es', 'CRI'),
  cTeDIvoireFrench('Côte d’Ivoire', 'French', 'fr', 'CI', 'fr', 'CIV'),
  croatiaCroatian('Croatia', 'Croatian', 'hr', 'HR', 'hr', 'HRV'),
  croatiaEnglish('Croatia', 'English', 'en', 'HR', 'en', 'HRV'),
  cubaSpanish('Cuba', 'Spanish', 'es', 'CU', 'es', 'CUB'),
  curaAoDutch('Curaçao', 'Dutch', 'nl', 'CW', 'nl', 'CUW'),
  curaAoSpanish('Curaçao', 'Spanish', 'es', 'CW', 'es', 'CUW'),
  cyprusEnglish('Cyprus', 'English', 'en', 'CY', 'en', 'CYP'),
  cyprusGreek('Cyprus', 'Greek', 'el', 'CY', 'el', 'CYP'),
  cyprusTurkish('Cyprus', 'Turkish', 'tr', 'CY', 'tr', 'CYP'),
  czechiaCzech('Czechia', 'Czech', 'cs', 'CZ', 'cs', 'CZE'),
  czechiaEnglish('Czechia', 'English', 'en', 'CZ', 'en', 'CZE'),
  denmarkDanish('Denmark', 'Danish', 'da', 'DK', 'da', 'DNK'),
  denmarkEnglish('Denmark', 'English', 'en', 'DK', 'en', 'DNK'),
  denmarkFaroese('Denmark', 'Faroese', 'fo', 'DK', 'fo', 'DNK'),
  diegoGarciaEnglish('Diego Garcia', 'English', 'en', 'DG', 'en', 'DGA'),
  djiboutiArabic('Djibouti', 'Arabic', 'ar', 'DJ', 'ar', 'DJI'),
  djiboutiFrench('Djibouti', 'French', 'fr', 'DJ', 'fr', 'DJI'),
  djiboutiSomali('Djibouti', 'Somali', 'so', 'DJ', 'so', 'DJI'),
  dominicaEnglish('Dominica', 'English', 'en', 'DM', 'en', 'DMA'),
  dominicaSpanish('Dominica', 'Spanish', 'es', 'DM', 'es', 'DMA'),
  dominicanRepublicSpanish('Dominican Republic', 'Spanish', 'es', 'DO', 'es', 'DOM'),
  ecuadorQuechua('Ecuador', 'Quechua', 'qu', 'EC', 'qu', 'ECU'),
  ecuadorSpanish('Ecuador', 'Spanish', 'es', 'EC', 'es', 'ECU'),
  egyptArabic('Egypt', 'Arabic', 'ar', 'EG', 'ar', 'EGY'),
  elSalvadorSpanish('El Salvador', 'Spanish', 'es', 'SV', 'es', 'SLV'),
  equatorialGuineaFrench('Equatorial Guinea', 'French', 'fr', 'GQ', 'fr', 'GNQ'),
  equatorialGuineaPortuguese('Equatorial Guinea', 'Portuguese', 'pt', 'GQ', 'pt', 'GNQ'),
  equatorialGuineaSpanish('Equatorial Guinea', 'Spanish', 'es', 'GQ', 'es', 'GNQ'),
  eritreaArabic('Eritrea', 'Arabic', 'ar', 'ER', 'ar', 'ERI'),
  eritreaBlin('Eritrea', 'Blin', 'byn', 'ER', 'byn', 'ERI'),
  eritreaEnglish('Eritrea', 'English', 'en', 'ER', 'en', 'ERI'),
  eritreaGeez('Eritrea', 'Geez', 'gez', 'ER', 'gez', 'ERI'),
  eritreaTigre('Eritrea', 'Tigre', 'tig', 'ER', 'tig', 'ERI'),
  eritreaTigrinya('Eritrea', 'Tigrinya', 'ti', 'ER', 'ti', 'ERI'),
  estoniaEnglish('Estonia', 'English', 'en', 'EE', 'en', 'EST'),
  estoniaEstonian('Estonia', 'Estonian', 'et', 'EE', 'et', 'EST'),
  eswatiniEnglish('Eswatini', 'English', 'en', 'SZ', 'en', 'SWZ'),
  eswatiniSwati('Eswatini', 'Swati', 'ss', 'SZ', 'ss', 'SWZ'),
  ethiopiaAmharic('Ethiopia', 'Amharic', 'am', 'ET', 'am', 'ETH'),
  ethiopiaGeez('Ethiopia', 'Geez', 'gez', 'ET', 'gez', 'ETH'),
  ethiopiaOromo('Ethiopia', 'Oromo', 'om', 'ET', 'om', 'ETH'),
  ethiopiaSomali('Ethiopia', 'Somali', 'so', 'ET', 'so', 'ETH'),
  ethiopiaTigrinya('Ethiopia', 'Tigrinya', 'ti', 'ET', 'ti', 'ETH'),
  ethiopiaWolaytta('Ethiopia', 'Wolaytta', 'wal', 'ET', 'wal', 'ETH'),
  europeEnglish('Europe', 'English', 'en', '150', 'en', ''),
  falklandIslandsEnglish('Falkland Islands', 'English', 'en', 'FK', 'en', 'FLK'),
  falklandIslandsSpanish('Falkland Islands', 'Spanish', 'es', 'FK', 'es', 'FLK'),
  faroeIslandsFaroese('Faroe Islands', 'Faroese', 'fo', 'FO', 'fo', 'FRO'),
  fijiEnglish('Fiji', 'English', 'en', 'FJ', 'en', 'FJI'),
  finlandEnglish('Finland', 'English', 'en', 'FI', 'en', 'FIN'),
  finlandFinnish('Finland', 'Finnish', 'fi', 'FI', 'fi', 'FIN'),
  finlandInariSami('Finland', 'Inari Sami', 'smn', 'FI', 'smn', 'FIN'),
  finlandNorthernSami('Finland', 'Northern Sami', 'se', 'FI', 'se', 'FIN'),
  finlandSwedish('Finland', 'Swedish', 'sv', 'FI', 'sv', 'FIN'),
  franceBreton('France', 'Breton', 'br', 'FR', 'br', 'FRA'),
  franceCatalan('France', 'Catalan', 'ca', 'FR', 'ca', 'FRA'),
  franceCorsican('France', 'Corsican', 'co', 'FR', 'co', 'FRA'),
  franceEnglish('France', 'English', 'en', 'FR', 'en', 'FRA'),
  franceFrench('France', 'French', 'fr', 'FR', 'fr', 'FRA'),
  franceOccitan('France', 'Occitan', 'oc', 'FR', 'oc', 'FRA'),
  francePortuguese('France', 'Portuguese', 'pt', 'FR', 'pt', 'FRA'),
  franceSwissGerman('France', 'Swiss German', 'gsw', 'FR', 'gsw', 'FRA'),
  frenchGuianaFrench('French Guiana', 'French', 'fr', 'GF', 'fr', 'GUF'),
  frenchGuianaSpanish('French Guiana', 'Spanish', 'es', 'GF', 'es', 'GUF'),
  frenchPolynesiaFrench('French Polynesia', 'French', 'fr', 'PF', 'fr', 'PYF'),
  gabonFrench('Gabon', 'French', 'fr', 'GA', 'fr', 'GAB'),
  gambiaEnglish('Gambia', 'English', 'en', 'GM', 'en', 'GMB'),
  gambiaFulah('Gambia', 'Fulah', 'ff', 'GM', 'ff', 'GMB'),
  georgiaGeorgian('Georgia', 'Georgian', 'ka', 'GE', 'ka', 'GEO'),
  georgiaOssetic('Georgia', 'Ossetic', 'os', 'GE', 'os', 'GEO'),
  germanyColognian('Germany', 'Colognian', 'ksh', 'DE', 'ksh', 'DEU'),
  germanyEnglish('Germany', 'English', 'en', 'DE', 'en', 'DEU'),
  germanyGerman('Germany', 'German', 'de', 'DE', 'de', 'DEU'),
  germanyLowGerman('Germany', 'Low German', 'nds', 'DE', 'nds', 'DEU'),
  germanyLowerSorbian('Germany', 'Lower Sorbian', 'dsb', 'DE', 'dsb', 'DEU'),
  germanyUpperSorbian('Germany', 'Upper Sorbian', 'hsb', 'DE', 'hsb', 'DEU'),
  ghanaAkan('Ghana', 'Akan', 'ak', 'GH', 'ak', 'GHA'),
  ghanaEnglish('Ghana', 'English', 'en', 'GH', 'en', 'GHA'),
  ghanaEwe('Ghana', 'Ewe', 'ee', 'GH', 'ee', 'GHA'),
  ghanaFulah('Ghana', 'Fulah', 'ff', 'GH', 'ff', 'GHA'),
  ghanaGa('Ghana', 'Ga', 'gaa', 'GH', 'gaa', 'GHA'),
  ghanaHausa('Ghana', 'Hausa', 'ha', 'GH', 'ha', 'GHA'),
  gibraltarEnglish('Gibraltar', 'English', 'en', 'GI', 'en', 'GIB'),
  greeceEnglish('Greece', 'English', 'en', 'GR', 'en', 'GRC'),
  greeceGreek('Greece', 'Greek', 'el', 'GR', 'el', 'GRC'),
  greenlandDanish('Greenland', 'Danish', 'da', 'GL', 'da', 'GRL'),
  greenlandKalaallisut('Greenland', 'Kalaallisut', 'kl', 'GL', 'kl', 'GRL'),
  greenlandSpanish('Greenland', 'Spanish', 'es', 'GL', 'es', 'GRL'),
  grenadaEnglish('Grenada', 'English', 'en', 'GD', 'en', 'GRD'),
  grenadaSpanish('Grenada', 'Spanish', 'es', 'GD', 'es', 'GRD'),
  guadeloupeFrench('Guadeloupe', 'French', 'fr', 'GP', 'fr', 'GLP'),
  guadeloupeSpanish('Guadeloupe', 'Spanish', 'es', 'GP', 'es', 'GLP'),
  guamEnglish('Guam', 'English', 'en', 'GU', 'en', 'GUM'),
  guatemalaSpanish('Guatemala', 'Spanish', 'es', 'GT', 'es', 'GTM'),
  guernseyEnglish('Guernsey', 'English', 'en', 'GG', 'en', 'GGY'),
  guineaFrench('Guinea', 'French', 'fr', 'GN', 'fr', 'GIN'),
  guineaFulah('Guinea', 'Fulah', 'ff', 'GN', 'ff', 'GIN'),
  guineaKpelle('Guinea', 'Kpelle', 'kpe', 'GN', 'kpe', 'GIN'),
  guineaNKo('Guinea', 'N\'Ko', 'nqo', 'GN', 'nqo', 'GIN'),
  guineaBissauFulah('Guinea-Bissau', 'Fulah', 'ff', 'GW', 'ff', 'GNB'),
  guineaBissauPortuguese('Guinea-Bissau', 'Portuguese', 'pt', 'GW', 'pt', 'GNB'),
  guyanaEnglish('Guyana', 'English', 'en', 'GY', 'en', 'GUY'),
  guyanaSpanish('Guyana', 'Spanish', 'es', 'GY', 'es', 'GUY'),
  haitiFrench('Haiti', 'French', 'fr', 'HT', 'fr', 'HTI'),
  haitiSpanish('Haiti', 'Spanish', 'es', 'HT', 'es', 'HTI'),
  hondurasSpanish('Honduras', 'Spanish', 'es', 'HN', 'es', 'HND'),
  hongKongCantonese('Hong Kong', 'Cantonese', 'yue', 'HK', 'yue', 'HKG'),
  hongKongChinese('Hong Kong', 'Chinese', 'zh', 'HK', 'zh', 'HKG'),
  hongKongEnglish('Hong Kong', 'English', 'en', 'HK', 'en', 'HKG'),
  hungaryEnglish('Hungary', 'English', 'en', 'HU', 'en', 'HUN'),
  hungaryHungarian('Hungary', 'Hungarian', 'hu', 'HU', 'hu', 'HUN'),
  icelandEnglish('Iceland', 'English', 'en', 'IS', 'en', 'ISL'),
  icelandIcelandic('Iceland', 'Icelandic', 'is', 'IS', 'is', 'ISL'),
  indiaAssamese('India', 'Assamese', 'as', 'IN', 'as', 'IND'),
  indiaBangla('India', 'Bangla', 'bn', 'IN', 'bn', 'IND'),
  indiaBodo('India', 'Bodo', 'brx', 'IN', 'brx', 'IND'),
  indiaChakma('India', 'Chakma', 'ccp', 'IN', 'ccp', 'IND'),
  indiaEnglish('India', 'English', 'en', 'IN', 'en', 'IND'),
  indiaGujarati('India', 'Gujarati', 'gu', 'IN', 'gu', 'IND'),
  indiaHindi('India', 'Hindi', 'hi', 'IN', 'hi', 'IND'),
  indiaKannada('India', 'Kannada', 'kn', 'IN', 'kn', 'IND'),
  indiaKashmiri('India', 'Kashmiri', 'ks', 'IN', 'ks', 'IND'),
  indiaKonkani('India', 'Konkani', 'kok', 'IN', 'kok', 'IND'),
  indiaMalayalam('India', 'Malayalam', 'ml', 'IN', 'ml', 'IND'),
  indiaManipuri('India', 'Manipuri', 'mni', 'IN', 'mni', 'IND'),
  indiaMarathi('India', 'Marathi', 'mr', 'IN', 'mr', 'IND'),
  indiaNepali('India', 'Nepali', 'ne', 'IN', 'ne', 'IND'),
  indiaOdia('India', 'Odia', 'or', 'IN', 'or', 'IND'),
  indiaPunjabi('India', 'Punjabi', 'pa', 'IN', 'pa', 'IND'),
  indiaSanskrit('India', 'Sanskrit', 'sa', 'IN', 'sa', 'IND'),
  indiaSantali('India', 'Santali', 'sat', 'IN', 'sat', 'IND'),
  indiaTamil('India', 'Tamil', 'ta', 'IN', 'ta', 'IND'),
  indiaTelugu('India', 'Telugu', 'te', 'IN', 'te', 'IND'),
  indiaTibetan('India', 'Tibetan', 'bo', 'IN', 'bo', 'IND'),
  indiaUrdu('India', 'Urdu', 'ur', 'IN', 'ur', 'IND'),
  indonesiaEnglish('Indonesia', 'English', 'en', 'ID', 'en', 'IDN'),
  indonesiaIndonesian('Indonesia', 'Indonesian', 'id', 'ID', 'id', 'IDN'),
  indonesiaJavanese('Indonesia', 'Javanese', 'jv', 'ID', 'jv', 'IDN'),
  iranKurdishSorani('Iran', 'Kurdish, Sorani', 'ckb', 'IR', 'ckb', 'IRN'),
  iranMazanderani('Iran', 'Mazanderani', 'mzn', 'IR', 'mzn', 'IRN'),
  iranNorthernLuri('Iran', 'Northern Luri', 'lrc', 'IR', 'lrc', 'IRN'),
  iranPersian('Iran', 'Persian', 'fa', 'IR', 'fa', 'IRN'),
  iraqArabic('Iraq', 'Arabic', 'ar', 'IQ', 'ar', 'IRQ'),
  iraqKurdishSorani('Iraq', 'Kurdish, Sorani', 'ckb', 'IQ', 'ckb', 'IRQ'),
  iraqNorthernLuri('Iraq', 'Northern Luri', 'lrc', 'IQ', 'lrc', 'IRQ'),
  iraqSyriac('Iraq', 'Syriac', 'syr', 'IQ', 'syr', 'IRQ'),
  irelandEnglish('Ireland', 'English', 'en', 'IE', 'en', 'IRL'),
  irelandIrish('Ireland', 'Irish', 'ga', 'IE', 'ga', 'IRL'),
  isleOfManEnglish('Isle of Man', 'English', 'en', 'IM', 'en', 'IMN'),
  isleOfManManx('Isle of Man', 'Manx', 'gv', 'IM', 'gv', 'IMN'),
  israelArabic('Israel', 'Arabic', 'ar', 'IL', 'ar', 'ISR'),
  israelEnglish('Israel', 'English', 'en', 'IL', 'en', 'ISR'),
  israelHebrew('Israel', 'Hebrew', 'he', 'IL', 'he', 'ISR'),
  italyCatalan('Italy', 'Catalan', 'ca', 'IT', 'ca', 'ITA'),
  italyEnglish('Italy', 'English', 'en', 'IT', 'en', 'ITA'),
  italyFriulian('Italy', 'Friulian', 'fur', 'IT', 'fur', 'ITA'),
  italyGerman('Italy', 'German', 'de', 'IT', 'de', 'ITA'),
  italyItalian('Italy', 'Italian', 'it', 'IT', 'it', 'ITA'),
  italySardinian('Italy', 'Sardinian', 'sc', 'IT', 'sc', 'ITA'),
  italySicilian('Italy', 'Sicilian', 'scn', 'IT', 'scn', 'ITA'),
  jamaicaEnglish('Jamaica', 'English', 'en', 'JM', 'en', 'JAM'),
  japanEnglish('Japan', 'English', 'en', 'JP', 'en', 'JPN'),
  japanJapanese('Japan', 'Japanese', 'ja', 'JP', 'ja', 'JPN'),
  jerseyEnglish('Jersey', 'English', 'en', 'JE', 'en', 'JEY'),
  jordanArabic('Jordan', 'Arabic', 'ar', 'JO', 'ar', 'JOR'),
  kazakhstanKazakh('Kazakhstan', 'Kazakh', 'kk', 'KZ', 'kk', 'KAZ'),
  kazakhstanRussian('Kazakhstan', 'Russian', 'ru', 'KZ', 'ru', 'KAZ'),
  kenyaEmbu('Kenya', 'Embu', 'ebu', 'KE', 'ebu', 'KEN'),
  kenyaEnglish('Kenya', 'English', 'en', 'KE', 'en', 'KEN'),
  kenyaGusii('Kenya', 'Gusii', 'guz', 'KE', 'guz', 'KEN'),
  kenyaKalenjin('Kenya', 'Kalenjin', 'kln', 'KE', 'kln', 'KEN'),
  kenyaKamba('Kenya', 'Kamba', 'kam', 'KE', 'kam', 'KEN'),
  kenyaKikuyu('Kenya', 'Kikuyu', 'ki', 'KE', 'ki', 'KEN'),
  kenyaLuo('Kenya', 'Luo', 'luo', 'KE', 'luo', 'KEN'),
  kenyaLuyia('Kenya', 'Luyia', 'luy', 'KE', 'luy', 'KEN'),
  kenyaMasai('Kenya', 'Masai', 'mas', 'KE', 'mas', 'KEN'),
  kenyaMeru('Kenya', 'Meru', 'mer', 'KE', 'mer', 'KEN'),
  kenyaOromo('Kenya', 'Oromo', 'om', 'KE', 'om', 'KEN'),
  kenyaSamburu('Kenya', 'Samburu', 'saq', 'KE', 'saq', 'KEN'),
  kenyaSomali('Kenya', 'Somali', 'so', 'KE', 'so', 'KEN'),
  kenyaSwahili('Kenya', 'Swahili', 'sw', 'KE', 'sw', 'KEN'),
  kenyaTaita('Kenya', 'Taita', 'dav', 'KE', 'dav', 'KEN'),
  kenyaTeso('Kenya', 'Teso', 'teo', 'KE', 'teo', 'KEN'),
  kiribatiEnglish('Kiribati', 'English', 'en', 'KI', 'en', 'KIR'),
  kosovoAlbanian('Kosovo', 'Albanian', 'sq', 'XK', 'sq', 'XKK'),
  kosovoSerbian('Kosovo', 'Serbian', 'sr', 'XK', 'sr', 'XKK'),
  kuwaitArabic('Kuwait', 'Arabic', 'ar', 'KW', 'ar', 'KWT'),
  kyrgyzstanKyrgyz('Kyrgyzstan', 'Kyrgyz', 'ky', 'KG', 'ky', 'KGZ'),
  kyrgyzstanRussian('Kyrgyzstan', 'Russian', 'ru', 'KG', 'ru', 'KGZ'),
  laosLao('Laos', 'Lao', 'lo', 'LA', 'lo', 'LAO'),
  latinAmericaSpanish('Latin America', 'Spanish', 'es', '419', 'es', ''),
  latviaEnglish('Latvia', 'English', 'en', 'LV', 'en', 'LVA'),
  latviaLatvian('Latvia', 'Latvian', 'lv', 'LV', 'lv', 'LVA'),
  lebanonArabic('Lebanon', 'Arabic', 'ar', 'LB', 'ar', 'LBN'),
  lesothoEnglish('Lesotho', 'English', 'en', 'LS', 'en', 'LSO'),
  lesothoSouthernSotho('Lesotho', 'Southern Sotho', 'st', 'LS', 'st', 'LSO'),
  liberiaEnglish('Liberia', 'English', 'en', 'LR', 'en', 'LBR'),
  liberiaFulah('Liberia', 'Fulah', 'ff', 'LR', 'ff', 'LBR'),
  liberiaKpelle('Liberia', 'Kpelle', 'kpe', 'LR', 'kpe', 'LBR'),
  liberiaVai('Liberia', 'Vai', 'vai', 'LR', 'vai', 'LBR'),
  libyaArabic('Libya', 'Arabic', 'ar', 'LY', 'ar', 'LBY'),
  liechtensteinGerman('Liechtenstein', 'German', 'de', 'LI', 'de', 'LIE'),
  liechtensteinSwissGerman('Liechtenstein', 'Swiss German', 'gsw', 'LI', 'gsw', 'LIE'),
  lithuaniaEnglish('Lithuania', 'English', 'en', 'LT', 'en', 'LTU'),
  lithuaniaLithuanian('Lithuania', 'Lithuanian', 'lt', 'LT', 'lt', 'LTU'),
  luxembourgEnglish('Luxembourg', 'English', 'en', 'LU', 'en', 'LUX'),
  luxembourgFrench('Luxembourg', 'French', 'fr', 'LU', 'fr', 'LUX'),
  luxembourgGerman('Luxembourg', 'German', 'de', 'LU', 'de', 'LUX'),
  luxembourgLuxembourgish('Luxembourg', 'Luxembourgish', 'lb', 'LU', 'lb', 'LUX'),
  luxembourgPortuguese('Luxembourg', 'Portuguese', 'pt', 'LU', 'pt', 'LUX'),
  macaoChinese('Macao', 'Chinese', 'zh', 'MO', 'zh', 'MAC'),
  macaoEnglish('Macao', 'English', 'en', 'MO', 'en', 'MAC'),
  macaoPortuguese('Macao', 'Portuguese', 'pt', 'MO', 'pt', 'MAC'),
  madagascarEnglish('Madagascar', 'English', 'en', 'MG', 'en', 'MDG'),
  madagascarFrench('Madagascar', 'French', 'fr', 'MG', 'fr', 'MDG'),
  madagascarMalagasy('Madagascar', 'Malagasy', 'mg', 'MG', 'mg', 'MDG'),
  malawiEnglish('Malawi', 'English', 'en', 'MW', 'en', 'MWI'),
  malawiNyanja('Malawi', 'Nyanja', 'ny', 'MW', 'ny', 'MWI'),
  malaysiaEnglish('Malaysia', 'English', 'en', 'MY', 'en', 'MYS'),
  malaysiaMalay('Malaysia', 'Malay', 'ms', 'MY', 'ms', 'MYS'),
  malaysiaTamil('Malaysia', 'Tamil', 'ta', 'MY', 'ta', 'MYS'),
  maldivesDhivehi('Maldives', 'Dhivehi', 'dv', 'MV', 'dv', 'MDV'),
  maldivesEnglish('Maldives', 'English', 'en', 'MV', 'en', 'MDV'),
  maliBambara('Mali', 'Bambara', 'bm', 'ML', 'bm', 'MLI'),
  maliFrench('Mali', 'French', 'fr', 'ML', 'fr', 'MLI'),
  maliKoyraChiini('Mali', 'Koyra Chiini', 'khq', 'ML', 'khq', 'MLI'),
  maliKoyraboroSenni('Mali', 'Koyraboro Senni', 'ses', 'ML', 'ses', 'MLI'),
  maltaEnglish('Malta', 'English', 'en', 'MT', 'en', 'MLT'),
  maltaMaltese('Malta', 'Maltese', 'mt', 'MT', 'mt', 'MLT'),
  marshallIslandsEnglish('Marshall Islands', 'English', 'en', 'MH', 'en', 'MHL'),
  martiniqueFrench('Martinique', 'French', 'fr', 'MQ', 'fr', 'MTQ'),
  martiniqueSpanish('Martinique', 'Spanish', 'es', 'MQ', 'es', 'MTQ'),
  mauritaniaArabic('Mauritania', 'Arabic', 'ar', 'MR', 'ar', 'MRT'),
  mauritaniaFrench('Mauritania', 'French', 'fr', 'MR', 'fr', 'MRT'),
  mauritaniaFulah('Mauritania', 'Fulah', 'ff', 'MR', 'ff', 'MRT'),
  mauritiusEnglish('Mauritius', 'English', 'en', 'MU', 'en', 'MUS'),
  mauritiusFrench('Mauritius', 'French', 'fr', 'MU', 'fr', 'MUS'),
  mauritiusMorisyen('Mauritius', 'Morisyen', 'mfe', 'MU', 'mfe', 'MUS'),
  mayotteFrench('Mayotte', 'French', 'fr', 'YT', 'fr', 'MYT'),
  mexicoEnglish('Mexico', 'English', 'en', 'MX', 'en', 'MEX'),
  mexicoSpanish('Mexico', 'Spanish', 'es', 'MX', 'es', 'MEX'),
  micronesiaEnglish('Micronesia', 'English', 'en', 'FM', 'en', 'FSM'),
  moldovaRomanian('Moldova', 'Romanian', 'ro', 'MD', 'ro', 'MDA'),
  moldovaRussian('Moldova', 'Russian', 'ru', 'MD', 'ru', 'MDA'),
  monacoFrench('Monaco', 'French', 'fr', 'MC', 'fr', 'MCO'),
  mongoliaMongolian('Mongolia', 'Mongolian', 'mn', 'MN', 'mn', 'MNG'),
  montenegroEnglish('Montenegro', 'English', 'en', 'ME', 'en', 'MNE'),
  montenegroSerbian('Montenegro', 'Serbian', 'sr', 'ME', 'sr', 'MNE'),
  montserratEnglish('Montserrat', 'English', 'en', 'MS', 'en', 'MSR'),
  montserratSpanish('Montserrat', 'Spanish', 'es', 'MS', 'es', 'MSR'),
  moroccoArabic('Morocco', 'Arabic', 'ar', 'MA', 'ar', 'MAR'),
  moroccoCentralAtlasTamazight('Morocco', 'Central Atlas Tamazight', 'tzm', 'MA', 'tzm', 'MAR'),
  moroccoFrench('Morocco', 'French', 'fr', 'MA', 'fr', 'MAR'),
  moroccoStandardMoroccanTamazight('Morocco', 'Standard Moroccan Tamazight', 'zgh', 'MA', 'zgh', 'MAR'),
  moroccoTachelhit('Morocco', 'Tachelhit', 'shi', 'MA', 'shi', 'MAR'),
  mozambiqueMakhuwaMeetto('Mozambique', 'Makhuwa-Meetto', 'mgh', 'MZ', 'mgh', 'MOZ'),
  mozambiquePortuguese('Mozambique', 'Portuguese', 'pt', 'MZ', 'pt', 'MOZ'),
  mozambiqueSena('Mozambique', 'Sena', 'seh', 'MZ', 'seh', 'MOZ'),
  myanmarBurmaBurmese('Myanmar (Burma)', 'Burmese', 'my', 'MM', 'my', 'MMR'),
  myanmarBurmaEnglish('Myanmar (Burma)', 'English', 'en', 'MM', 'en', 'MMR'),
  namibiaAfrikaans('Namibia', 'Afrikaans', 'af', 'NA', 'af', 'NAM'),
  namibiaEnglish('Namibia', 'English', 'en', 'NA', 'en', 'NAM'),
  namibiaNama('Namibia', 'Nama', 'naq', 'NA', 'naq', 'NAM'),
  nauruEnglish('Nauru', 'English', 'en', 'NR', 'en', 'NRU'),
  nepalNepali('Nepal', 'Nepali', 'ne', 'NP', 'ne', 'NPL'),
  netherlandsDutch('Netherlands', 'Dutch', 'nl', 'NL', 'nl', 'NLD'),
  netherlandsEnglish('Netherlands', 'English', 'en', 'NL', 'en', 'NLD'),
  netherlandsLowGerman('Netherlands', 'Low German', 'nds', 'NL', 'nds', 'NLD'),
  netherlandsWesternFrisian('Netherlands', 'Western Frisian', 'fy', 'NL', 'fy', 'NLD'),
  newCaledoniaFrench('New Caledonia', 'French', 'fr', 'NC', 'fr', 'NCL'),
  newZealandEnglish('New Zealand', 'English', 'en', 'NZ', 'en', 'NZL'),
  newZealandMaori('New Zealand', 'Maori', 'mi', 'NZ', 'mi', 'NZL'),
  nicaraguaSpanish('Nicaragua', 'Spanish', 'es', 'NI', 'es', 'NIC'),
  nigerFrench('Niger', 'French', 'fr', 'NE', 'fr', 'NER'),
  nigerFulah('Niger', 'Fulah', 'ff', 'NE', 'ff', 'NER'),
  nigerHausa('Niger', 'Hausa', 'ha', 'NE', 'ha', 'NER'),
  nigerTasawaq('Niger', 'Tasawaq', 'twq', 'NE', 'twq', 'NER'),
  nigerZarma('Niger', 'Zarma', 'dje', 'NE', 'dje', 'NER'),
  nigeriaEnglish('Nigeria', 'English', 'en', 'NG', 'en', 'NGA'),
  nigeriaFulah('Nigeria', 'Fulah', 'ff', 'NG', 'ff', 'NGA'),
  nigeriaHausa('Nigeria', 'Hausa', 'ha', 'NG', 'ha', 'NGA'),
  nigeriaIgbo('Nigeria', 'Igbo', 'ig', 'NG', 'ig', 'NGA'),
  nigeriaJju('Nigeria', 'Jju', 'kaj', 'NG', 'kaj', 'NGA'),
  nigeriaTyap('Nigeria', 'Tyap', 'kcg', 'NG', 'kcg', 'NGA'),
  nigeriaYoruba('Nigeria', 'Yoruba', 'yo', 'NG', 'yo', 'NGA'),
  niueEnglish('Niue', 'English', 'en', 'NU', 'en', 'NIU'),
  norfolkIslandEnglish('Norfolk Island', 'English', 'en', 'NF', 'en', 'NFK'),
  northKoreaKorean('North Korea', 'Korean', 'ko', 'KP', 'ko', 'PRK'),
  northMacedoniaAlbanian('North Macedonia', 'Albanian', 'sq', 'MK', 'sq', 'MKD'),
  northMacedoniaMacedonian('North Macedonia', 'Macedonian', 'mk', 'MK', 'mk', 'MKD'),
  northernMarianaIslandsEnglish('Northern Mariana Islands', 'English', 'en', 'MP', 'en', 'MNP'),
  norwayEnglish('Norway', 'English', 'en', 'NO', 'en', 'NOR'),
  norwayNorthernSami('Norway', 'Northern Sami', 'se', 'NO', 'se', 'NOR'),
  norwayNorwegianBokmL('Norway', 'Norwegian Bokmål', 'nb', 'NO', 'nb', 'NOR'),
  norwayNorwegianNynorsk('Norway', 'Norwegian Nynorsk', 'nn', 'NO', 'nn', 'NOR'),
  omanArabic('Oman', 'Arabic', 'ar', 'OM', 'ar', 'OMN'),
  pakistanEnglish('Pakistan', 'English', 'en', 'PK', 'en', 'PAK'),
  pakistanPashto('Pakistan', 'Pashto', 'ps', 'PK', 'ps', 'PAK'),
  pakistanPunjabi('Pakistan', 'Punjabi', 'pa', 'PK', 'pa', 'PAK'),
  pakistanSindhi('Pakistan', 'Sindhi', 'sd', 'PK', 'sd', 'PAK'),
  pakistanUrdu('Pakistan', 'Urdu', 'ur', 'PK', 'ur', 'PAK'),
  palauEnglish('Palau', 'English', 'en', 'PW', 'en', 'PLW'),
  palestinianTerritoriesArabic('Palestinian Territories', 'Arabic', 'ar', 'PS', 'ar', 'PSE'),
  panamaSpanish('Panama', 'Spanish', 'es', 'PA', 'es', 'PAN'),
  papuaNewGuineaEnglish('Papua New Guinea', 'English', 'en', 'PG', 'en', 'PNG'),
  paraguayGuarani('Paraguay', 'Guarani', 'gn', 'PY', 'gn', 'PRY'),
  paraguaySpanish('Paraguay', 'Spanish', 'es', 'PY', 'es', 'PRY'),
  peruQuechua('Peru', 'Quechua', 'qu', 'PE', 'qu', 'PER'),
  peruSpanish('Peru', 'Spanish', 'es', 'PE', 'es', 'PER'),
  philippinesCebuano('Philippines', 'Cebuano', 'ceb', 'PH', 'ceb', 'PHL'),
  philippinesEnglish('Philippines', 'English', 'en', 'PH', 'en', 'PHL'),
  philippinesFilipino('Philippines', 'Filipino', 'fil', 'PH', 'fil', 'PHL'),
  philippinesSpanish('Philippines', 'Spanish', 'es', 'PH', 'es', 'PHL'),
  pitcairnIslandsEnglish('Pitcairn Islands', 'English', 'en', 'PN', 'en', 'PCN'),
  polandEnglish('Poland', 'English', 'en', 'PL', 'en', 'POL'),
  polandPolish('Poland', 'Polish', 'pl', 'PL', 'pl', 'POL'),
  portugalEnglish('Portugal', 'English', 'en', 'PT', 'en', 'PRT'),
  portugalPortuguese('Portugal', 'Portuguese', 'pt', 'PT', 'pt', 'PRT'),
  puertoRicoEnglish('Puerto Rico', 'English', 'en', 'PR', 'en', 'PRI'),
  puertoRicoSpanish('Puerto Rico', 'Spanish', 'es', 'PR', 'es', 'PRI'),
  qatarArabic('Qatar', 'Arabic', 'ar', 'QA', 'ar', 'QAT'),
  rUnionFrench('Réunion', 'French', 'fr', 'RE', 'fr', 'REU'),
  romaniaEnglish('Romania', 'English', 'en', 'RO', 'en', 'ROU'),
  romaniaRomanian('Romania', 'Romanian', 'ro', 'RO', 'ro', 'ROU'),
  russiaBashkir('Russia', 'Bashkir', 'ba', 'RU', 'ba', 'RUS'),
  russiaChechen('Russia', 'Chechen', 'ce', 'RU', 'ce', 'RUS'),
  russiaChuvash('Russia', 'Chuvash', 'cv', 'RU', 'cv', 'RUS'),
  russiaEnglish('Russia', 'English', 'en', 'RU', 'en', 'RUS'),
  russiaErzya('Russia', 'Erzya', 'myv', 'RU', 'myv', 'RUS'),
  russiaOssetic('Russia', 'Ossetic', 'os', 'RU', 'os', 'RUS'),
  russiaRussian('Russia', 'Russian', 'ru', 'RU', 'ru', 'RUS'),
  russiaSakha('Russia', 'Sakha', 'sah', 'RU', 'sah', 'RUS'),
  russiaTatar('Russia', 'Tatar', 'tt', 'RU', 'tt', 'RUS'),
  rwandaEnglish('Rwanda', 'English', 'en', 'RW', 'en', 'RWA'),
  rwandaFrench('Rwanda', 'French', 'fr', 'RW', 'fr', 'RWA'),
  rwandaKinyarwanda('Rwanda', 'Kinyarwanda', 'rw', 'RW', 'rw', 'RWA'),
  samoaEnglish('Samoa', 'English', 'en', 'WS', 'en', 'WSM'),
  sanMarinoItalian('San Marino', 'Italian', 'it', 'SM', 'it', 'SMR'),
  sOTomPrNcipePortuguese('São Tomé & Príncipe', 'Portuguese', 'pt', 'ST', 'pt', 'STP'),
  saudiArabiaArabic('Saudi Arabia', 'Arabic', 'ar', 'SA', 'ar', 'SAU'),
  saudiArabiaEnglish('Saudi Arabia', 'English', 'en', 'SA', 'en', 'SAU'),
  senegalFrench('Senegal', 'French', 'fr', 'SN', 'fr', 'SEN'),
  senegalFulah('Senegal', 'Fulah', 'ff', 'SN', 'ff', 'SEN'),
  senegalJolaFonyi('Senegal', 'Jola-Fonyi', 'dyo', 'SN', 'dyo', 'SEN'),
  senegalWolof('Senegal', 'Wolof', 'wo', 'SN', 'wo', 'SEN'),
  serbiaEnglish('Serbia', 'English', 'en', 'RS', 'en', 'SRB'),
  serbiaSerbian('Serbia', 'Serbian', 'sr', 'RS', 'sr', 'SRB'),
  seychellesEnglish('Seychelles', 'English', 'en', 'SC', 'en', 'SYC'),
  seychellesFrench('Seychelles', 'French', 'fr', 'SC', 'fr', 'SYC'),
  sierraLeoneEnglish('Sierra Leone', 'English', 'en', 'SL', 'en', 'SLE'),
  sierraLeoneFulah('Sierra Leone', 'Fulah', 'ff', 'SL', 'ff', 'SLE'),
  singaporeChinese('Singapore', 'Chinese', 'zh', 'SG', 'zh', 'SGP'),
  singaporeEnglish('Singapore', 'English', 'en', 'SG', 'en', 'SGP'),
  singaporeMalay('Singapore', 'Malay', 'ms', 'SG', 'ms', 'SGP'),
  singaporeTamil('Singapore', 'Tamil', 'ta', 'SG', 'ta', 'SGP'),
  sintMaartenDutch('Sint Maarten', 'Dutch', 'nl', 'SX', 'nl', 'SXM'),
  sintMaartenEnglish('Sint Maarten', 'English', 'en', 'SX', 'en', 'SXM'),
  sintMaartenSpanish('Sint Maarten', 'Spanish', 'es', 'SX', 'es', 'SXM'),
  slovakiaEnglish('Slovakia', 'English', 'en', 'SK', 'en', 'SVK'),
  slovakiaSlovak('Slovakia', 'Slovak', 'sk', 'SK', 'sk', 'SVK'),
  sloveniaEnglish('Slovenia', 'English', 'en', 'SI', 'en', 'SVN'),
  sloveniaSlovenian('Slovenia', 'Slovenian', 'sl', 'SI', 'sl', 'SVN'),
  solomonIslandsEnglish('Solomon Islands', 'English', 'en', 'SB', 'en', 'SLB'),
  somaliaArabic('Somalia', 'Arabic', 'ar', 'SO', 'ar', 'SOM'),
  somaliaSomali('Somalia', 'Somali', 'so', 'SO', 'so', 'SOM'),
  southAfricaAfrikaans('South Africa', 'Afrikaans', 'af', 'ZA', 'af', 'ZAF'),
  southAfricaEnglish('South Africa', 'English', 'en', 'ZA', 'en', 'ZAF'),
  southAfricaNorthernSotho('South Africa', 'Northern Sotho', 'nso', 'ZA', 'nso', 'ZAF'),
  southAfricaSouthNdebele('South Africa', 'South Ndebele', 'nr', 'ZA', 'nr', 'ZAF'),
  southAfricaSouthernSotho('South Africa', 'Southern Sotho', 'st', 'ZA', 'st', 'ZAF'),
  southAfricaSwati('South Africa', 'Swati', 'ss', 'ZA', 'ss', 'ZAF'),
  southAfricaTsonga('South Africa', 'Tsonga', 'ts', 'ZA', 'ts', 'ZAF'),
  southAfricaTswana('South Africa', 'Tswana', 'tn', 'ZA', 'tn', 'ZAF'),
  southAfricaVenda('South Africa', 'Venda', 've', 'ZA', 've', 'ZAF'),
  southAfricaXhosa('South Africa', 'Xhosa', 'xh', 'ZA', 'xh', 'ZAF'),
  southAfricaZulu('South Africa', 'Zulu', 'zu', 'ZA', 'zu', 'ZAF'),
  southKoreaEnglish('South Korea', 'English', 'en', 'KR', 'en', 'KOR'),
  southKoreaKorean('South Korea', 'Korean', 'ko', 'KR', 'ko', 'KOR'),
  southSudanArabic('South Sudan', 'Arabic', 'ar', 'SS', 'ar', 'SSD'),
  southSudanEnglish('South Sudan', 'English', 'en', 'SS', 'en', 'SSD'),
  southSudanNuer('South Sudan', 'Nuer', 'nus', 'SS', 'nus', 'SSD'),
  spainAsturian('Spain', 'Asturian', 'ast', 'ES', 'ast', 'ESP'),
  spainBasque('Spain', 'Basque', 'eu', 'ES', 'eu', 'ESP'),
  spainCatalan('Spain', 'Catalan', 'ca', 'ES', 'ca', 'ESP'),
  spainEnglish('Spain', 'English', 'en', 'ES', 'en', 'ESP'),
  spainGalician('Spain', 'Galician', 'gl', 'ES', 'gl', 'ESP'),
  spainSpanish('Spain', 'Spanish', 'es', 'ES', 'es', 'ESP'),
  sriLankaSinhala('Sri Lanka', 'Sinhala', 'si', 'LK', 'si', 'LKA'),
  sriLankaTamil('Sri Lanka', 'Tamil', 'ta', 'LK', 'ta', 'LKA'),
  stBarthLemyFrench('St. Barthélemy', 'French', 'fr', 'BL', 'fr', 'BLM'),
  stBarthLemySpanish('St. Barthélemy', 'Spanish', 'es', 'BL', 'es', 'BLM'),
  stHelenaEnglish('St. Helena', 'English', 'en', 'SH', 'en', 'SHN'),
  stKittsNevisEnglish('St. Kitts & Nevis', 'English', 'en', 'KN', 'en', 'KNA'),
  stKittsNevisSpanish('St. Kitts & Nevis', 'Spanish', 'es', 'KN', 'es', 'KNA'),
  stLuciaEnglish('St. Lucia', 'English', 'en', 'LC', 'en', 'LCA'),
  stLuciaSpanish('St. Lucia', 'Spanish', 'es', 'LC', 'es', 'LCA'),
  stMartinFrench('St. Martin', 'French', 'fr', 'MF', 'fr', 'MAF'),
  stMartinSpanish('St. Martin', 'Spanish', 'es', 'MF', 'es', 'MAF'),
  stPierreMiquelonFrench('St. Pierre & Miquelon', 'French', 'fr', 'PM', 'fr', 'SPM'),
  stPierreMiquelonSpanish('St. Pierre & Miquelon', 'Spanish', 'es', 'PM', 'es', 'SPM'),
  stVincentGrenadinesEnglish('St. Vincent & Grenadines', 'English', 'en', 'VC', 'en', 'VCT'),
  stVincentGrenadinesSpanish('St. Vincent & Grenadines', 'Spanish', 'es', 'VC', 'es', 'VCT'),
  sudanArabic('Sudan', 'Arabic', 'ar', 'SD', 'ar', 'SDN'),
  sudanEnglish('Sudan', 'English', 'en', 'SD', 'en', 'SDN'),
  surinameDutch('Suriname', 'Dutch', 'nl', 'SR', 'nl', 'SUR'),
  surinameSpanish('Suriname', 'Spanish', 'es', 'SR', 'es', 'SUR'),
  svalbardJanMayenNorwegianBokmL('Svalbard & Jan Mayen', 'Norwegian Bokmål', 'nb', 'SJ', 'nb', 'SJM'),
  swedenEnglish('Sweden', 'English', 'en', 'SE', 'en', 'SWE'),
  swedenNorthernSami('Sweden', 'Northern Sami', 'se', 'SE', 'se', 'SWE'),
  swedenSwedish('Sweden', 'Swedish', 'sv', 'SE', 'sv', 'SWE'),
  switzerlandEnglish('Switzerland', 'English', 'en', 'CH', 'en', 'CHE'),
  switzerlandFrench('Switzerland', 'French', 'fr', 'CH', 'fr', 'CHE'),
  switzerlandGerman('Switzerland', 'German', 'de', 'CH', 'de', 'CHE'),
  switzerlandItalian('Switzerland', 'Italian', 'it', 'CH', 'it', 'CHE'),
  switzerlandPortuguese('Switzerland', 'Portuguese', 'pt', 'CH', 'pt', 'CHE'),
  switzerlandRomansh('Switzerland', 'Romansh', 'rm', 'CH', 'rm', 'CHE'),
  switzerlandSwissGerman('Switzerland', 'Swiss German', 'gsw', 'CH', 'gsw', 'CHE'),
  switzerlandWalser('Switzerland', 'Walser', 'wae', 'CH', 'wae', 'CHE'),
  syriaArabic('Syria', 'Arabic', 'ar', 'SY', 'ar', 'SYR'),
  syriaFrench('Syria', 'French', 'fr', 'SY', 'fr', 'SYR'),
  syriaSyriac('Syria', 'Syriac', 'syr', 'SY', 'syr', 'SYR'),
  taiwanChinese('Taiwan', 'Chinese', 'zh', 'TW', 'zh', 'TWN'),
  taiwanEnglish('Taiwan', 'English', 'en', 'TW', 'en', 'TWN'),
  taiwanTaroko('Taiwan', 'Taroko', 'trv', 'TW', 'trv', 'TWN'),
  tajikistanTajik('Tajikistan', 'Tajik', 'tg', 'TJ', 'tg', 'TJK'),
  tanzaniaAsu('Tanzania', 'Asu', 'asa', 'TZ', 'asa', 'TZA'),
  tanzaniaBena('Tanzania', 'Bena', 'bez', 'TZ', 'bez', 'TZA'),
  tanzaniaEnglish('Tanzania', 'English', 'en', 'TZ', 'en', 'TZA'),
  tanzaniaLangi('Tanzania', 'Langi', 'lag', 'TZ', 'lag', 'TZA'),
  tanzaniaMachame('Tanzania', 'Machame', 'jmc', 'TZ', 'jmc', 'TZA'),
  tanzaniaMakonde('Tanzania', 'Makonde', 'kde', 'TZ', 'kde', 'TZA'),
  tanzaniaMasai('Tanzania', 'Masai', 'mas', 'TZ', 'mas', 'TZA'),
  tanzaniaRombo('Tanzania', 'Rombo', 'rof', 'TZ', 'rof', 'TZA'),
  tanzaniaRwa('Tanzania', 'Rwa', 'rwk', 'TZ', 'rwk', 'TZA'),
  tanzaniaSangu('Tanzania', 'Sangu', 'sbp', 'TZ', 'sbp', 'TZA'),
  tanzaniaShambala('Tanzania', 'Shambala', 'ksb', 'TZ', 'ksb', 'TZA'),
  tanzaniaSwahili('Tanzania', 'Swahili', 'sw', 'TZ', 'sw', 'TZA'),
  tanzaniaVunjo('Tanzania', 'Vunjo', 'vun', 'TZ', 'vun', 'TZA'),
  thailandEnglish('Thailand', 'English', 'en', 'TH', 'en', 'THA'),
  thailandThai('Thailand', 'Thai', 'th', 'TH', 'th', 'THA'),
  timorLestePortuguese('Timor-Leste', 'Portuguese', 'pt', 'TL', 'pt', 'TLS'),
  togoEwe('Togo', 'Ewe', 'ee', 'TG', 'ee', 'TGO'),
  togoFrench('Togo', 'French', 'fr', 'TG', 'fr', 'TGO'),
  tokelauEnglish('Tokelau', 'English', 'en', 'TK', 'en', 'TKL'),
  tongaEnglish('Tonga', 'English', 'en', 'TO', 'en', 'TON'),
  tongaTongan('Tonga', 'Tongan', 'to', 'TO', 'to', 'TON'),
  trinidadTobagoEnglish('Trinidad & Tobago', 'English', 'en', 'TT', 'en', 'TTO'),
  trinidadTobagoSpanish('Trinidad & Tobago', 'Spanish', 'es', 'TT', 'es', 'TTO'),
  tunisiaArabic('Tunisia', 'Arabic', 'ar', 'TN', 'ar', 'TUN'),
  tunisiaFrench('Tunisia', 'French', 'fr', 'TN', 'fr', 'TUN'),
  turkeyEnglish('Turkey', 'English', 'en', 'TR', 'en', 'TUR'),
  turkeyKurdish('Turkey', 'Kurdish', 'ku', 'TR', 'ku', 'TUR'),
  turkeyTurkish('Turkey', 'Turkish', 'tr', 'TR', 'tr', 'TUR'),
  turkmenistanTurkmen('Turkmenistan', 'Turkmen', 'tk', 'TM', 'tk', 'TKM'),
  turksCaicosIslandsEnglish('Turks & Caicos Islands', 'English', 'en', 'TC', 'en', 'TCA'),
  turksCaicosIslandsSpanish('Turks & Caicos Islands', 'Spanish', 'es', 'TC', 'es', 'TCA'),
  tuvaluEnglish('Tuvalu', 'English', 'en', 'TV', 'en', 'TUV'),
  uSOutlyingIslandsEnglish('U.S. Outlying Islands', 'English', 'en', 'UM', 'en', 'UMI'),
  uSVirginIslandsEnglish('U.S. Virgin Islands', 'English', 'en', 'VI', 'en', 'VIR'),
  uSVirginIslandsSpanish('U.S. Virgin Islands', 'Spanish', 'es', 'VI', 'es', 'VIR'),
  ugandaChiga('Uganda', 'Chiga', 'cgg', 'UG', 'cgg', 'UGA'),
  ugandaEnglish('Uganda', 'English', 'en', 'UG', 'en', 'UGA'),
  ugandaGanda('Uganda', 'Ganda', 'lg', 'UG', 'lg', 'UGA'),
  ugandaNyankole('Uganda', 'Nyankole', 'nyn', 'UG', 'nyn', 'UGA'),
  ugandaSoga('Uganda', 'Soga', 'xog', 'UG', 'xog', 'UGA'),
  ugandaSwahili('Uganda', 'Swahili', 'sw', 'UG', 'sw', 'UGA'),
  ugandaTeso('Uganda', 'Teso', 'teo', 'UG', 'teo', 'UGA'),
  ukraineEnglish('Ukraine', 'English', 'en', 'UA', 'en', 'UKR'),
  ukraineRussian('Ukraine', 'Russian', 'ru', 'UA', 'ru', 'UKR'),
  ukraineUkrainian('Ukraine', 'Ukrainian', 'uk', 'UA', 'uk', 'UKR'),
  unitedArabEmiratesArabic('United Arab Emirates', 'Arabic', 'ar', 'AE', 'ar', 'ARE'),
  unitedArabEmiratesEnglish('United Arab Emirates', 'English', 'en', 'AE', 'en', 'ARE'),
  unitedKingdomCornish('United Kingdom', 'Cornish', 'kw', 'GB', 'kw', 'GBR'),
  unitedKingdomEnglish('United Kingdom', 'English', 'en', 'GB', 'en', 'GBR'),
  unitedKingdomScottishGaelic('United Kingdom', 'Scottish Gaelic', 'gd', 'GB', 'gd', 'GBR'),
  unitedKingdomWelsh('United Kingdom', 'Welsh', 'cy', 'GB', 'cy', 'GBR'),
  unitedStatesCherokee('United States', 'Cherokee', 'chr', 'US', 'chr', 'USA'),
  unitedStatesEnglishUnitedStates('United States', 'English (United States)', 'en', 'US', 'en', 'USA'),
  unitedStatesEnglish('United States', 'English', 'en', 'US', 'en', 'USA'),
  unitedStatesHawaiian('United States', 'Hawaiian', 'haw', 'US', 'haw', 'USA'),
  unitedStatesLakota('United States', 'Lakota', 'lkt', 'US', 'lkt', 'USA'),
  unitedStatesSpanish('United States', 'Spanish', 'es', 'US', 'es', 'USA'),
  uruguaySpanish('Uruguay', 'Spanish', 'es', 'UY', 'es', 'URY'),
  uzbekistanUzbek('Uzbekistan', 'Uzbek', 'uz', 'UZ', 'uz', 'UZB'),
  vanuatuEnglish('Vanuatu', 'English', 'en', 'VU', 'en', 'VUT'),
  vanuatuFrench('Vanuatu', 'French', 'fr', 'VU', 'fr', 'VUT'),
  vaticanCityItalian('Vatican City', 'Italian', 'it', 'VA', 'it', 'VAT'),
  venezuelaSpanish('Venezuela', 'Spanish', 'es', 'VE', 'es', 'VEN'),
  vietnamVietnamese('Vietnam', 'Vietnamese', 'vi', 'VN', 'vi', 'VNM'),
  wallisFutunaFrench('Wallis & Futuna', 'French', 'fr', 'WF', 'fr', 'WLF'),
  westernSaharaArabic('Western Sahara', 'Arabic', 'ar', 'EH', 'ar', 'ESH'),
  worldArabic('World', 'Arabic', 'ar', '001', 'ar', ''),
  worldEnglish('World', 'English', 'en', '001', 'en', ''),
  worldEsperanto('World', 'Esperanto', 'eo', '001', 'eo', ''),
  worldIdo('World', 'Ido', 'io', '001', 'io', ''),
  worldInterlingua('World', 'Interlingua', 'ia', '001', 'ia', ''),
  worldLojban('World', 'Lojban', 'jbo', '001', 'jbo', ''),
  worldYiddish('World', 'Yiddish', 'yi', '001', 'yi', ''),
  yemenArabic('Yemen', 'Arabic', 'ar', 'YE', 'ar', 'YEM'),
  zambiaBemba('Zambia', 'Bemba', 'bem', 'ZM', 'bem', 'ZMB'),
  zambiaEnglish('Zambia', 'English', 'en', 'ZM', 'en', 'ZMB'),
  zimbabweEnglish('Zimbabwe', 'English', 'en', 'ZW', 'en', 'ZWE'),
  zimbabweNorthNdebele('Zimbabwe', 'North Ndebele', 'nd', 'ZW', 'nd', 'ZWE'),
  zimbabweShona('Zimbabwe', 'Shona', 'sn', 'ZW', 'sn', 'ZWE');

  const LanguageType(
    this.country,
    this.language,
    this.twoLetterLanguageCode,
    this.twoLetterCountryCode,
    this.threeLetterLanguageCode,
    this.threeLetterCountryCode,
  );
  final String country;
  final String language;
  final String twoLetterLanguageCode;
  final String twoLetterCountryCode;
  final String threeLetterLanguageCode;
  final String threeLetterCountryCode;

  factory LanguageType.fromFormattedString(String value) {
    List<String> splittedLanguage = value.split('-');

    String country = splittedLanguage[0];
    String language = splittedLanguage[1];
    String twoLetterLanguageCode = splittedLanguage[2];
    String twoLetterCountryCode = splittedLanguage[3];
    String threeLetterLanguageCode = splittedLanguage[4];
    String threeLetterCountryCode = splittedLanguage[5];

    return values.trySingleWhere((element) => element.country == country && element.language == language && element.twoLetterLanguageCode == twoLetterLanguageCode && element.twoLetterCountryCode == twoLetterCountryCode && element.threeLetterLanguageCode == threeLetterLanguageCode && element.threeLetterCountryCode == threeLetterCountryCode) ?? unitedStatesEnglish;
  }

  String toFormattedString() => '$country-$language-$twoLetterLanguageCode-$twoLetterCountryCode-$threeLetterLanguageCode-$threeLetterCountryCode';

  static LanguageType? fromCountry(String country) => LanguageType.values.trySingleWhere((element) => element.country == country);

  static LanguageType? fromLanguage(String language) => LanguageType.values.trySingleWhere((element) => element.language == language);

  static LanguageType? fromTwoLetterLanguageCode(String code) => LanguageType.values.trySingleWhere((element) => element.twoLetterLanguageCode == code);

  static LanguageType? fromTwoLetterCountryCode(String code) => LanguageType.values.trySingleWhere((element) => element.twoLetterCountryCode == code);

  static LanguageType? fromThreeLetterLanguageCode(String code) => LanguageType.values.trySingleWhere((element) => element.threeLetterLanguageCode == code);

  static LanguageType? fromThreeLetterCountryCode(String code) => LanguageType.values.trySingleWhere((element) => element.threeLetterCountryCode == code);
}
