part of 'utils.dart';

/// A utility class for generating random Firestore document IDs.
///
/// The `FirestoreAutoIdGenerator` class provides a simple way to generate random and unique document IDs
/// that can be used as keys when adding documents to a Firestore collection. The IDs generated by this class
/// are 20 characters long and consist of a combination of uppercase letters, lowercase letters, and numbers.
///
/// The [autoId] method can be called to automatically generate a new random ID each time it is invoked.
///
/// Example usage:
/// ```dart
/// String newDocumentId = FirestoreAutoIdGenerator.autoId();
/// ```
class FirestoreAutoIdGenerator {
  static const int _autoIDLength = 20;

  static const String _autoIdAlphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

  static final Random _random = Random();

  /// Automatically generates a random new Firestore document ID.
  ///
  /// The generated ID is 20 characters long and consists of a combination of uppercase letters,
  /// lowercase letters, and numbers.
  ///
  /// Example usage:
  /// ```dart
  /// String newDocumentId = FirestoreAutoIdGenerator.autoId();
  /// ```
  static String autoId() {
    final StringBuffer stringBuffer = StringBuffer();
    const int maxRandom = _autoIdAlphabet.length;

    for (int i = 0; i < _autoIDLength; ++i) {
      stringBuffer.write(_autoIdAlphabet[_random.nextInt(maxRandom)]);
    }

    return stringBuffer.toString();
  }
}
